Repository AvlasenkoPetr/rslang, pull requests merged in 2022-02, with the labels that each got.

#11 RSL-04
  rslang/package-lock.json
  rslang/src/assets/images/background-guys/girl-on-chair.svg
  rslang/src/assets/images/background-guys/man-on-chair.svg
  rslang/src/assets/images/book.svg
  rslang/src/assets/images/games.svg
  rslang/src/assets/images/home.svg
  rslang/src/assets/images/rsschool.svg
  rslang/src/assets/images/stats.svg
  rslang/src/assets/images/team.svg
  rslang/src/assets/styles/default.scss
  rslang/src/components/footer/footer.scss
  rslang/src/components/footer/footer.ts
  rslang/src/components/pages/login-page/login-page.scss
  rslang/src/components/pages/login-page/login-page.ts
  rslang/src/components/pages/main-page/main-page.scss
  rslang/src/components/pages/main-page/main-page.ts
  rslang/src/components/router/router.scss
  rslang/src/components/router/router.ts
  rslang/src/index.html
  rslang/src/index.ts
Labels: feat

#16 RSL 11
  rslang/src/components/Fetch/fetch.ts
  rslang/src/components/Helpers/helpers.ts
  rslang/src/components/Interfaces/interfaces.ts
  rslang/src/index.ts
Labels: fix

#19 RSL-09
  rslang/package-lock.json
  rslang/package.json
  rslang/src/assets/images/background-guys/man-reading-newspaper.svg
  rslang/src/assets/images/background-waves/level-page-wave.svg
  rslang/src/components/footer/footer.ts
  rslang/src/components/pages/level-page/level-page.scss
  rslang/src/components/pages/level-page/level-page.ts
  rslang/src/components/pages/login-page/login-page.ts
  rslang/src/components/pages/main-page/main-page.ts
  rslang/src/components/router/router.ts
  rslang/src/index.html
Labels: feat

#33 RSL-09
  rslang/src/components/pages/games/audiocall/audioCallGame.ts
  rslang/src/components/pages/games/audiocall/gamePage.ts
  rslang/src/components/pages/level-page/level-page.scss
  rslang/src/components/pages/level-page/level-page.ts
  rslang/src/components/router/router.ts
  rslang/src/index.ts
Labels: feat

#36 Rsl 02 sprint
  rslang/src/assets/images/navigation/audiocall.svg
  rslang/src/assets/images/navigation/sprint.svg
  rslang/src/assets/images/sprint/arr-left.svg
  rslang/src/assets/images/sprint/arr-right.svg
  rslang/src/assets/images/sprint/audio-off.svg
  rslang/src/assets/images/sprint/audio-on.svg
  rslang/src/assets/images/sprint/fullscreen-off.svg
  rslang/src/assets/images/sprint/fullscreen-on.svg
  rslang/src/assets/images/sprint/sprint-bg.jpg
  rslang/src/assets/images/sprint/timer.svg
  rslang/src/assets/sounds/correct.mp3
  rslang/src/assets/sounds/incorrect.mp3
  rslang/src/components/Interfaces/interfaces.ts
  rslang/src/components/Reusable-components/GameResult/gameResult.scss
  rslang/src/components/Reusable-components/GameResult/gameResult.ts
  rslang/src/components/pages/games/audiocall/audioCallGame.ts
  rslang/src/components/pages/games/sprint/sprint.scss
  rslang/src/components/pages/games/sprint/sprint.ts
  rslang/src/components/pages/level-page/level-page.scss
  rslang/src/components/pages/level-page/level-page.ts
  rslang/src/components/router/router.scss
  rslang/src/components/router/router.ts
  rslang/src/index.html
Labels: feat

#43 Rsl-03
  rslang/src/components/Reusable-components/spinner/spinner.scss
  rslang/src/components/Reusable-components/spinner/spinner.ts
  rslang/src/components/pages/games/sprint/sprint.ts
  rslang/src/components/pages/level-page/level-page.ts
Labels: feat

#53 Rsl 17
  rslang/src/components/Interfaces/interfaces.ts
  rslang/src/components/Reusable-components/GameResult/gameResult.ts
  rslang/src/components/pages/book-page/book-page.ts
  rslang/src/components/pages/games/sprint/sprint.ts
  rslang/src/components/pages/level-page/level-page.ts
Labels: feat

#57 fix: remove currentPage from LS
  rslang/src/components/Reusable-components/GameResult/gameResult.ts
  rslang/src/components/pages/level-page/level-page.ts
Labels: fix

#62 RSL-24
  rslang/src/components/pages/games/sprint/sprint.ts
  rslang/src/components/pages/main-page/main-page.scss
Labels: feat

#63 fix: fix keyboard control
  rslang/src/components/pages/games/sprint/sprint.ts
Labels: feat

#67 feat: add date in option word
  rslang/src/components/Helpers/helpers.ts
  rslang/src/components/pages/games/sprint/sprint.ts
Labels: feat

#70 Rsl 28
  rslang/src/components/pages/games/sprint/sprint.ts
Labels: hotfix

#71 Rsl 28
  rslang/src/assets/images/favicon.ico
  rslang/src/components/pages/games/sprint/sprint.ts
  rslang/src/index.html
Labels: fix

#74 RSL-29
  rslang/src/components/pages/games/sprint/sprint.ts
Labels: fix
